name: Manual Merge

on:
  workflow_dispatch: # This allows the workflow to be triggered manually

jobs:
  run-merge-script:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Run merge script
        run: python merge.py