name: Update Google Sheet with Vulnerability Data

on:
  push:
    paths:
      - merged_vulnerability_data.csv  # Trigger action when this file is updated

jobs:
  update-google-sheet:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Python script to process the CSV file and convert it to a format for Google Sheets
      - name: Run CSV to Google Sheets Script
        run: |
          pip install pandas gspread oauth2client
          python process_and_update_gsheet.py 

      # GSheet Action to update the Google Sheet
      - name: Update Google Sheet
        uses: ethomson/gsheet-action@v1
        with:
          credentials: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}  # Google Sheets API credentials
          spreadsheet-id: 'your-google-sheet-id'  
          range: 'Sheet1!A1'  
          input-file: 'output/merged_vulnerability_data.csv'  